export const templates = [
  {
    id: "cinematic-product-reveal",
    title: "Cinematic Product Reveal",
    description: "Slow dramatic reveal with cinematic lighting and depth of field",
    category: "Product Ads",
    model: "seedance",
    mode: "image-to-video",
    prompt: "Slow cinematic reveal of the product emerging from darkness, dramatic volumetric lighting, shallow depth of field, luxury feel, 4K quality, smooth camera movement pulling back to reveal full product",
    image: "/nova/nova-seedance-pro.png",
    tags: ["cinematic", "luxury", "reveal"],
  },
  {
    id: "luxury-closeup-shot",
    title: "Luxury Close-up Shot",
    description: "Premium macro detail shot for high-end products",
    category: "Product Ads",
    model: "kling",
    mode: "image-to-video",
    prompt: "Extreme close-up macro shot of product surface, premium materials texture detail, soft bokeh background, elegant slow rotation, luxury brand aesthetic, warm golden hour lighting",
    image: "/nova/nova-kling-3.png",
    tags: ["luxury", "macro", "detail"],
  },
  {
    id: "ugc-unboxing-style",
    title: "UGC Unboxing Style",
    description: "Authentic user-generated content style unboxing video",
    category: "UGC",
    model: "seedance",
    mode: "text-to-video",
    prompt: "Authentic UGC style unboxing video, handheld camera feel, natural indoor lighting, person opening premium package, genuine excited reaction, close-up of product being revealed, real and relatable",
    image: "/nova/nova-seedance-fast.png",
    tags: ["ugc", "unboxing", "authentic"],
  },
  {
    id: "lifestyle-background-swap",
    title: "Lifestyle Background",
    description: "Place your product in a premium lifestyle setting",
    category: "E-commerce",
    model: "veo",
    mode: "image-to-video",
    prompt: "Product placed in aspirational lifestyle environment, natural soft light, modern minimal interior, slight camera drift, premium e-commerce aesthetic, clean and professional",
    image: "/nova/nova-veo-3-1.png",
    tags: ["lifestyle", "e-commerce", "clean"],
  },
  {
    id: "smoke-glow-effect",
    title: "Smoke & Glow Effect",
    description: "Mystical smoke and neon glow visual effects around product",
    category: "Visual FX",
    model: "happyhorse",
    mode: "image-to-video",
    prompt: "Product surrounded by mystical colored smoke wisps, ethereal neon glow radiating outward, particles floating in slow motion, dark dramatic background, magical atmosphere",
    image: "/nova/nova-seedance-fast.png",
    tags: ["fx", "glow", "smoke"],
  },
  {
    id: "fast-cut-social-hook",
    title: "Fast Cut Social Hook",
    description: "High-energy quick cuts optimized for social media hooks",
    category: "Social Media",
    model: "kling",
    mode: "text-to-video",
    prompt: "High energy fast cut video ad, dynamic transitions, bold text overlays, product featured prominently, trending social media aesthetic, attention-grabbing first 3 seconds, viral hook format",
    image: "/nova/nova-kling-3.png",
    tags: ["social", "fast", "hook"],
  },
  {
    id: "water-splash-product",
    title: "Water Splash Hero",
    description: "Dramatic water splash around product — great for beverages and skincare",
    category: "Visual FX",
    model: "seedance",
    mode: "image-to-video",
    prompt: "Product surrounded by dramatic water splash in slow motion, crystal clear droplets frozen in air, white clean background, refreshing and premium feel, high-speed camera effect",
    image: "/nova/nova-seedance-pro.png",
    tags: ["water", "splash", "beverage"],
  },
  {
    id: "360-product-spin",
    title: "360° Product Spin",
    description: "Clean rotating product shot, perfect for e-commerce listings",
    category: "E-commerce",
    model: "veo",
    mode: "image-to-video",
    prompt: "Perfect 360 degree smooth rotation of product on clean white or dark background, studio lighting setup, professional product photography in motion, e-commerce ready",
    image: "/nova/nova-veo-3-1.png",
    tags: ["360", "spin", "e-commerce"],
  },
  {
    id: "outdoor-adventure",
    title: "Outdoor Adventure",
    description: "Product in dynamic outdoor action setting",
    category: "Lifestyle",
    model: "wan",
    mode: "image-to-video",
    prompt: "Product featured in dramatic outdoor adventure setting, dynamic natural lighting, mountains or nature background, action and movement, rugged authentic feel, aspirational lifestyle",
    image: "/nova/nova-wan-2-6.png",
    tags: ["outdoor", "adventure", "lifestyle"],
  },
  {
    id: "minimalist-studio",
    title: "Minimalist Studio",
    description: "Clean minimal studio shot with subtle animation",
    category: "Product Ads",
    model: "seedance",
    mode: "image-to-video",
    prompt: "Minimalist product shot on seamless background, subtle floating animation, soft shadow, clean professional aesthetic, Scandinavian design influence, quiet luxury feel",
    image: "/nova/nova-seedance-pro.png",
    tags: ["minimal", "studio", "clean"],
  },
  {
    id: "golden-hour-glow",
    title: "Golden Hour Glow",
    description: "Warm golden hour sunlight aesthetic",
    category: "Lifestyle",
    model: "kling",
    mode: "image-to-video",
    prompt: "Product bathed in warm golden hour sunlight, lens flare effect, rich warm tones, outdoor setting with soft bokeh, romantic and aspirational atmosphere, sun rays streaming through",
    image: "/nova/nova-kling-3.png",
    tags: ["golden", "warm", "lifestyle"],
  },
  {
    id: "dark-dramatic",
    title: "Dark & Dramatic",
    description: "High contrast dark aesthetic for premium brands",
    category: "Product Ads",
    model: "kling",
    mode: "image-to-video",
    prompt: "Product in high contrast dark dramatic lighting, deep shadows with single strong light source, luxury brand noir aesthetic, mysterious and premium, cinematic color grade",
    image: "/nova/nova-kling-3.png",
    tags: ["dark", "dramatic", "premium"],
  },
];

export const categories = ["All", "Product Ads", "UGC", "E-commerce", "Visual FX", "Social Media", "Lifestyle"];
