export const TEMPLATE_CATEGORIES = [
  "All",
  "AI Dance",
  "Pet / Animals",
  "Mini-Me",
  "Anime",
  "Product Ads",
  "UGC Ads",
  "Image Editor",
  "Character Stories",
];

export const VIRAL_TEMPLATES = [
  {
    id: "animate-image-5s",
    name: "Animate Image 5s",
    category: "Anime",
    output: "video",
    workflow: "image-to-video",
    badge: "Essential",
    recommended: true,
    requiresImage: true,
    defaultDuration: 5,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Animate any image into a short cinematic video.",
    description:
      "Upload one image and turn it into a 5 second moving clip with camera motion, subtle expression and cinematic energy.",
    inputLabel: "Upload image to animate",
    hookPlaceholder: "Optional motion direction, e.g. slow camera push-in, blinking, wind in hair...",
    prompt:
      "Animate this image into a short cinematic clip. Keep the same subject, face, outfit, colors, composition and visual identity. Add natural subtle motion, cinematic camera movement and realistic depth. Do not change the main subject.",
  },
  {
    id: "pet-dance",
    name: "Pet Dance",
    category: "Pet / Animals",
    output: "video",
    workflow: "image-to-video",
    badge: "Viral",
    recommended: true,
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Make a pet look like it is dancing for a viral short.",
    description:
      "Upload a dog, cat or animal photo and generate a fun short-form pet dance video.",
    inputLabel: "Upload pet image",
    hookPlaceholder: "Optional hook, e.g. My dog when he hears his favorite song...",
    prompt:
      "Turn this pet into a funny viral dance video. Keep the same pet identity, fur colors, face and body features. Add playful rhythmic movement, upbeat social media energy, clean background motion and expressive personality. No text, no watermark.",
  },
  {
    id: "animal-talking-reaction",
    name: "Animal Talking Reaction",
    category: "Pet / Animals",
    output: "video",
    workflow: "image-to-video",
    badge: "Meme",
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Create a reaction-style animal clip.",
    description:
      "Upload a pet/animal photo and create a talking/reaction-style short for TikTok or Reels.",
    inputLabel: "Upload animal image",
    hookPlaceholder: "Write the reaction/hook, e.g. When mom says we are going to the park...",
    prompt:
      "Create a funny animal reaction video. Keep the same animal identity, face and colors. Add subtle mouth movement, head movement, expressive reaction and social-media meme timing. Make it feel like a short viral reaction clip.",
  },
  {
    id: "mini-me-dance",
    name: "Mini-Me Dance",
    category: "Mini-Me",
    output: "video",
    workflow: "image-then-video",
    badge: "Trend",
    recommended: true,
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Create a younger version dancing with the adult version.",
    description:
      "Upload a person image. NOVA creates a consistent adult + younger self scene and animates it.",
    inputLabel: "Upload person image",
    hookPlaceholder: "Optional hook, e.g. Dancing with the younger me who never gave up...",
    imagePrompt:
      "Create a scene with the person from the uploaded image standing beside a younger child version of themselves. Preserve the adult identity, face, hairstyle, body proportions and visual style. The younger version should clearly feel like the same person as a child. Both are ready to dance in a tasteful, positive, cinematic social media scene. No text, no watermark.",
    prompt:
      "Animate the adult person and their younger self dancing together in a heartwarming viral short. Keep both identities consistent. Add smooth dance movement, positive emotion, cinematic lighting and social-media pacing.",
  },
  {
    id: "younger-self-hug",
    name: "Younger Self Hug",
    category: "Mini-Me",
    output: "video",
    workflow: "image-then-video",
    badge: "Emotional",
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "A touching scene where the adult hugs their younger self.",
    description:
      "Creates an emotional storytelling clip with adult + childhood version.",
    inputLabel: "Upload person image",
    hookPlaceholder: "Optional hook, e.g. I finally told my younger self we made it...",
    imagePrompt:
      "Create an emotional cinematic scene where the person from the uploaded image gently hugs a younger child version of themselves. Preserve the adult identity, face, hair, outfit style and overall look. The younger self should look like a believable child version of the same person. Warm cinematic lighting. No text, no watermark.",
    prompt:
      "Animate this emotional scene with a gentle hug, subtle camera push-in, warm expression and cinematic lighting. Keep the adult and younger self identities consistent. Do not change faces or outfits.",
  },
  {
    id: "anime-portrait",
    name: "Anime Portrait",
    category: "Anime",
    output: "image",
    workflow: "image-edit",
    badge: "Anime",
    requiresImage: true,
    defaultRatio: "1:1",
    title: "Transform an uploaded image into a premium anime avatar.",
    description:
      "Upload a portrait or character image and convert it into a consistent anime-style avatar.",
    inputLabel: "Upload image",
    hookPlaceholder: "Optional direction, e.g. cyberpunk anime, soft studio anime, fantasy hero...",
    prompt:
      "Transform the uploaded image into a premium anime portrait while preserving the same identity, face structure, hairstyle, outfit color palette and composition. Clean anime linework, expressive eyes, cinematic lighting, no text, no watermark.",
  },
  {
    id: "anime-image-to-video",
    name: "Anime Image to Video",
    category: "Anime",
    output: "video",
    workflow: "image-then-video",
    badge: "Anime Video",
    requiresImage: true,
    defaultDuration: 5,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Turn a real image into anime, then animate it.",
    description:
      "Upload an image, create an anime version, and animate it into a short clip.",
    inputLabel: "Upload image",
    hookPlaceholder: "Optional motion, e.g. dramatic wind, blinking, cinematic camera move...",
    imagePrompt:
      "Convert this uploaded image into a high-quality anime scene. Preserve identity, subject, pose, composition, outfit colors and overall visual structure. Anime cinematic style, clean details, no text, no watermark.",
    prompt:
      "Animate this anime scene with subtle cinematic motion, natural expression, light movement and a smooth camera push. Keep the same character identity and composition.",
  },
  {
    id: "product-hook-ad",
    name: "Product Hook Ad",
    category: "Product Ads",
    output: "video",
    workflow: "image-to-video",
    badge: "Ad",
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Create a short product ad with a strong hook.",
    description:
      "Upload a product image and generate a TikTok/Reels-style ad clip around it.",
    inputLabel: "Upload product image",
    hookPlaceholder: "Write hook, e.g. This little gadget changed my mornings...",
    prompt:
      "Create a high-converting short product ad video. Keep the exact same product identity, shape, color and design. Use premium e-commerce lighting, dynamic product reveal, clean camera movement, social media pacing and direct-response energy. No fake claims.",
  },
  {
    id: "ugc-product-demo",
    name: "UGC Product Demo",
    category: "UGC Ads",
    output: "video",
    workflow: "image-to-video",
    badge: "UGC",
    recommended: true,
    requiresImage: true,
    defaultDuration: 10,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Make a UGC-style product demo from one image.",
    description:
      "Upload product or creator image and generate a user-generated-content style ad scene.",
    inputLabel: "Upload product or creator image",
    hookPlaceholder: "Write UGC hook, e.g. I did not expect this to work this well...",
    prompt:
      "Generate a realistic UGC product demo video. Keep the uploaded subject/product accurate. Create natural creator-style movement, handheld social media feel, strong visual hook, product desirability, and clear ad-ready framing. No text overlays, no watermark.",
  },
  {
    id: "before-after-transformation",
    name: "Before / After Transformation",
    category: "AI Dance",
    output: "video",
    workflow: "image-then-video",
    badge: "Trend",
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Create a glow-up transformation clip.",
    description:
      "Upload one image and turn it into a before/after social media transformation.",
    inputLabel: "Upload image",
    hookPlaceholder: "Optional hook, e.g. Wait for the transformation...",
    imagePrompt:
      "Create a premium glow-up transformation scene using the uploaded image as the identity reference. Preserve the same person or subject, but create a more polished after version with cinematic styling, better lighting and elevated presentation. No text, no watermark.",
    prompt:
      "Animate this transformation as a short viral before/after clip with a smooth reveal, energetic motion, cinematic lighting and social media pacing. Keep the same identity consistent.",
  },
  {
    id: "talking-photo",
    name: "Talking Photo",
    category: "AI Dance",
    output: "video",
    workflow: "image-to-video",
    badge: "Avatar",
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Animate a portrait as if it is speaking or reacting.",
    description:
      "Upload a portrait and create a subtle talking-head/reaction video.",
    inputLabel: "Upload portrait image",
    hookPlaceholder: "Write what the person should seem to say/react to...",
    prompt:
      "Animate this portrait into a subtle talking-head social media clip. Preserve the same face, identity, hairstyle, outfit and background. Add natural mouth movement, blinking, small head motion and expressive reaction. No text, no watermark.",
  },
  {
    id: "character-story-scene",
    name: "Character Story Scene",
    category: "Character Stories",
    output: "image",
    workflow: "image-edit",
    badge: "Story",
    requiresImage: true,
    defaultRatio: "9:16",
    title: "Generate a new story scene using the same character.",
    description:
      "Upload a character reference and generate a consistent new scene for storytelling.",
    inputLabel: "Upload character reference",
    hookPlaceholder: "Describe the scene, e.g. The hero enters a neon market at night...",
    prompt:
      "Create a new story scene using the uploaded character as the main subject. Preserve the same character identity, face, hairstyle, outfit, colors, proportions and visual style. Only change the pose, expression, camera angle and environment according to the user's scene. No text, no watermark.",
  },
  {
    id: "add-hook-to-image",
    name: "Add Hook to Image",
    category: "Image Editor",
    output: "image",
    workflow: "image-edit",
    badge: "Editor",
    requiresImage: true,
    defaultRatio: "9:16",
    title: "Add a hook/headline to an existing image.",
    description:
      "Upload an image and ask NOVA to add a social media hook while preserving the image.",
    inputLabel: "Upload image",
    hookPlaceholder: "Write exact hook, e.g. THIS CHANGED EVERYTHING",
    prompt:
      "Keep the uploaded image visually identical. Preserve the subject, background, colors, lighting and composition. Add the user's hook text as a clean bold social media headline in a tasteful position with strong readability. Do not change anything else.",
  },
  {
    id: "change-background",
    name: "Change Background",
    category: "Image Editor",
    output: "image",
    workflow: "image-edit",
    badge: "Editor",
    requiresImage: true,
    defaultRatio: "1:1",
    title: "Change only the background of an image.",
    description:
      "Keep the subject identical and replace only the background or setting.",
    inputLabel: "Upload image",
    hookPlaceholder: "Describe new background, e.g. luxury bedroom, neon city, beach sunset...",
    prompt:
      "Keep the main subject exactly the same, including face, pose, outfit, product details, lighting on the subject and proportions. Change only the background to match the user's request. Make the result realistic and professional. No text, no watermark.",
  },
  {
    id: "change-outfit",
    name: "Change Outfit",
    category: "Image Editor",
    output: "image",
    workflow: "image-edit",
    badge: "Editor",
    requiresImage: true,
    defaultRatio: "1:1",
    title: "Change only the outfit while keeping the person consistent.",
    description:
      "Useful for fashion, UGC, avatar and ad variations.",
    inputLabel: "Upload person image",
    hookPlaceholder: "Describe new outfit, e.g. black leather jacket, red dress, luxury suit...",
    prompt:
      "Keep the same person, face, body proportions, pose, hair, expression, camera angle and background. Change only the outfit according to the user's request. Make it realistic, consistent and high-quality. No text, no watermark.",
  },
  {
    id: "face-style-consistency",
    name: "Face / Character Consistency",
    category: "Image Editor",
    output: "image",
    workflow: "image-edit",
    badge: "Avatar",
    requiresImage: true,
    defaultRatio: "1:1",
    title: "Generate a new image while keeping the same face/identity.",
    description:
      "Use this when the goal is consistent avatars and story characters.",
    inputLabel: "Upload face / character reference",
    hookPlaceholder: "Describe the new pose, scene or expression...",
    prompt:
      "Use the uploaded image as the identity reference. Preserve the same face, character identity, hairstyle, proportions, outfit style and color palette. Generate the user's requested new pose/scene/expression while keeping the identity consistent. No text, no watermark.",
  },
  {
    id: "brand-mascot-video",
    name: "Brand Mascot Video",
    category: "Product Ads",
    output: "video",
    workflow: "image-to-video",
    badge: "Brand",
    requiresImage: true,
    defaultDuration: 8,
    defaultRatio: "9:16",
    defaultResolution: "480p",
    title: "Turn a mascot/product character into a branded video.",
    description:
      "Upload a mascot, product character, toy or logo-character and animate it.",
    inputLabel: "Upload mascot/product character",
    hookPlaceholder: "Optional hook, e.g. Meet the mascot behind the brand...",
    prompt:
      "Animate this mascot or product character into a premium short branded video. Preserve the same character design, colors, shape and identity. Add playful motion, clean product-ad framing, social media pacing and cinematic lighting. No watermark.",
  },
];

export function getTemplateById(id) {
  return VIRAL_TEMPLATES.find((template) => template.id === id) || VIRAL_TEMPLATES[0];
}
